language: c

# install all vnc-related dependencies
before_install:
  - sudo apt-get build-dep x11vnc

# before build script, run autoreconf
before_script: autoreconf -fiv

# Default is "./configure && make && make test", but no tests yet
script: "./configure && make"